language: php

php:
  - 5.5
  - 5.6

services:
  - mongodb

before_script:
  - echo 'extension = mongo.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer self-update
  - composer install --prefer-source

script:
    - vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
    - vendor/bin/phpcs --standard=PSR1 src tests
    - vendor/bin/phpcs --standard=PSR2 src tests

after_script: vendor/bin/coveralls -v
